apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-service-config
  namespace: cloud-service
data:
  config.json: |
    {
      "core": {
        "log_level": "info",
        "metrics_enabled": true,
        "performance_monitoring": true
      },
      "network": {
        "port": 8080,
        "max_connections": 10000,
        "timeout_ms": 30000,
        "use_dpdk": true
      },
      "blockchain": {
        "consensus": "pbft",
        "block_time_ms": 2000,
        "max_block_size": 5000000,
        "min_validators": 7
      },
      "storage": {
        "cache_size_mb": 16384,
        "use_numa": true,
        "persistence_path": "/var/lib/cloud-service/data"
      },
      "security": {
        "enclave_enabled": true,
        "tls_enabled": true,
        "cert_path": "/etc/cloud-service/certs"
      },
      "monitoring": {
        "prometheus_port": 9090,
        "jaeger_endpoint": "http://jaeger:14268/api/traces"
      },
      "kubernetes": {
        "enabled": true,
        "namespace": "cloud-service",
        "replicas": 3
      }
    } 